stages:
  preprocess:
    cmd: python preprocess.py
    deps:
      - preprocess.py
    outs:
      - data/preprocessed_churn.csv

  train:
    cmd: python train.py
    deps:
      - train.py
      - data/preprocessed_churn.csv